"""skema awal

Revision ID: 7c9a9f319843
Revises:
Create Date: 2026-08-31 18:38:27.397371
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "7c9a9f319843"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=True),
        sa.Column("resource_id", sa.String(length=128), nullable=True),
        sa.Column("detail", sa.JSON(), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_actor_id"), "audit_logs", ["actor_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=True)
    op.create_table(
        "ships",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("imo_number", sa.String(length=16), nullable=True),
        sa.Column("call_sign", sa.String(length=16), nullable=True),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("imo_number"),
    )
    op.create_index(op.f("ix_ships_name"), "ships", ["name"], unique=False)
    op.create_index(op.f("ix_ships_slug"), "ships", ["slug"], unique=True)
    op.create_table(
        "sync_batches",
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column("ship_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("sequence_start", sa.BigInteger(), nullable=False),
        sa.Column("sequence_end", sa.BigInteger(), nullable=False),
        sa.Column("first_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("record_count", sa.Integer(), nullable=False),
        sa.Column("payload_checksum", sa.String(length=80), nullable=False),
        sa.Column("payload_encoding", sa.String(length=32), nullable=False),
        sa.Column("payload_size", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("agent_version", sa.String(length=32), nullable=True),
        sa.Column("config_version", sa.String(length=64), nullable=True),
        sa.Column("transport", sa.String(length=16), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("committed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reject_reason", sa.Text(), nullable=True),
        sa.Column("ack_payload", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("batch_id"),
        sa.UniqueConstraint("ship_id", "sequence_start", "sequence_end", name="uq_batch_range"),
    )
    op.create_index(op.f("ix_sync_batches_device_id"), "sync_batches", ["device_id"], unique=False)
    op.create_index(op.f("ix_sync_batches_ship_id"), "sync_batches", ["ship_id"], unique=False)
    op.create_index(op.f("ix_sync_batches_status"), "sync_batches", ["status"], unique=False)
    op.create_table(
        "upload_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column("ship_id", sa.UUID(), nullable=False),
        sa.Column("envelope", sa.JSON(), nullable=False),
        sa.Column("chunk_size", sa.Integer(), nullable=False),
        sa.Column("total_chunks", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_upload_sessions_batch_id"), "upload_sessions", ["batch_id"], unique=True
    )
    op.create_index(
        op.f("ix_upload_sessions_ship_id"), "upload_sessions", ["ship_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=256), nullable=True),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "alert_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ship_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("metric", sa.String(length=64), nullable=False),
        sa.Column("sensor_id", sa.String(length=64), nullable=True),
        sa.Column("comparison", sa.String(length=8), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["ship_id"], ["ships.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alert_rules_ship_id"), "alert_rules", ["ship_id"], unique=False)
    op.create_table(
        "devices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ship_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("hardware", sa.String(length=128), nullable=True),
        sa.Column("field_device", sa.String(length=128), nullable=True),
        sa.Column("agent_version", sa.String(length=32), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["ship_id"], ["ships.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_devices_ship_id"), "devices", ["ship_id"], unique=False)
    op.create_table(
        "sensors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ship_id", sa.UUID(), nullable=False),
        sa.Column("sensor_id", sa.String(length=64), nullable=False),
        sa.Column("metric", sa.String(length=64), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=True),
        sa.Column("display_name", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("min_value", sa.Float(), nullable=True),
        sa.Column("max_value", sa.Float(), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["ship_id"], ["ships.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ship_id", "sensor_id", name="uq_sensor_per_ship"),
    )
    op.create_index(op.f("ix_sensors_sensor_id"), "sensors", ["sensor_id"], unique=False)
    op.create_index(op.f("ix_sensors_ship_id"), "sensors", ["ship_id"], unique=False)
    op.create_table(
        "ship_configs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ship_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["ship_id"], ["ships.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ship_id", "version", name="uq_config_version"),
    )
    op.create_index(op.f("ix_ship_configs_ship_id"), "ship_configs", ["ship_id"], unique=False)
    op.create_table(
        "ship_sync_state",
        sa.Column("ship_id", sa.UUID(), nullable=False),
        sa.Column("last_contiguous_sequence", sa.BigInteger(), nullable=False),
        sa.Column("highest_sequence_seen", sa.BigInteger(), nullable=False),
        sa.Column("last_batch_received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_telemetry_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pending_estimate", sa.BigInteger(), nullable=True),
        sa.Column("oldest_pending_age_seconds", sa.BigInteger(), nullable=True),
        sa.Column("connection_state", sa.String(length=16), nullable=False),
        sa.Column("active_transport", sa.String(length=16), nullable=True),
        sa.Column("edge_health", sa.JSON(), nullable=True),
        sa.Column("config_version", sa.String(length=64), nullable=True),
        sa.Column("agent_version", sa.String(length=32), nullable=True),
        sa.Column("total_batches", sa.BigInteger(), nullable=False),
        sa.Column("total_records", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["ship_id"], ["ships.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("ship_id"),
    )
    op.create_table(
        "upload_chunks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["session_id"], ["upload_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "chunk_index", name="uq_session_chunk"),
    )
    op.create_index(
        op.f("ix_upload_chunks_session_id"), "upload_chunks", ["session_id"], unique=False
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    op.create_table(
        "voyages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ship_id", sa.UUID(), nullable=False),
        sa.Column("voyage_number", sa.String(length=64), nullable=False),
        sa.Column("departure_port", sa.String(length=128), nullable=True),
        sa.Column("arrival_port", sa.String(length=128), nullable=True),
        sa.Column("departed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("arrived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["ship_id"], ["ships.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_voyages_ship_id"), "voyages", ["ship_id"], unique=False)
    op.create_table(
        "alert_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("rule_id", sa.UUID(), nullable=True),
        sa.Column("ship_id", sa.UUID(), nullable=False),
        sa.Column("sensor_id", sa.String(length=64), nullable=True),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["rule_id"], ["alert_rules.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_alert_events_occurred_at"), "alert_events", ["occurred_at"], unique=False
    )
    op.create_index(op.f("ix_alert_events_severity"), "alert_events", ["severity"], unique=False)
    op.create_index(op.f("ix_alert_events_ship_id"), "alert_events", ["ship_id"], unique=False)
    op.create_table(
        "device_credentials",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("ship_id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.String(length=64), nullable=False),
        sa.Column("secret_hash", sa.String(length=256), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_device_credentials_client_id"), "device_credentials", ["client_id"], unique=True
    )
    op.create_index(
        op.f("ix_device_credentials_device_id"), "device_credentials", ["device_id"], unique=False
    )
    op.create_index(
        op.f("ix_device_credentials_ship_id"), "device_credentials", ["ship_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_device_credentials_ship_id"), table_name="device_credentials")
    op.drop_index(op.f("ix_device_credentials_device_id"), table_name="device_credentials")
    op.drop_index(op.f("ix_device_credentials_client_id"), table_name="device_credentials")
    op.drop_table("device_credentials")
    op.drop_index(op.f("ix_alert_events_ship_id"), table_name="alert_events")
    op.drop_index(op.f("ix_alert_events_severity"), table_name="alert_events")
    op.drop_index(op.f("ix_alert_events_occurred_at"), table_name="alert_events")
    op.drop_table("alert_events")
    op.drop_index(op.f("ix_voyages_ship_id"), table_name="voyages")
    op.drop_table("voyages")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_upload_chunks_session_id"), table_name="upload_chunks")
    op.drop_table("upload_chunks")
    op.drop_table("ship_sync_state")
    op.drop_index(op.f("ix_ship_configs_ship_id"), table_name="ship_configs")
    op.drop_table("ship_configs")
    op.drop_index(op.f("ix_sensors_ship_id"), table_name="sensors")
    op.drop_index(op.f("ix_sensors_sensor_id"), table_name="sensors")
    op.drop_table("sensors")
    op.drop_index(op.f("ix_devices_ship_id"), table_name="devices")
    op.drop_table("devices")
    op.drop_index(op.f("ix_alert_rules_ship_id"), table_name="alert_rules")
    op.drop_table("alert_rules")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_upload_sessions_ship_id"), table_name="upload_sessions")
    op.drop_index(op.f("ix_upload_sessions_batch_id"), table_name="upload_sessions")
    op.drop_table("upload_sessions")
    op.drop_index(op.f("ix_sync_batches_status"), table_name="sync_batches")
    op.drop_index(op.f("ix_sync_batches_ship_id"), table_name="sync_batches")
    op.drop_index(op.f("ix_sync_batches_device_id"), table_name="sync_batches")
    op.drop_table("sync_batches")
    op.drop_index(op.f("ix_ships_slug"), table_name="ships")
    op.drop_index(op.f("ix_ships_name"), table_name="ships")
    op.drop_table("ships")
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
